### ISSUE TITLE
Latest release has a version collide with PHPStan

### ISSUE THREAD

**Issue by michielgerritsen** [fooman/phpstan-magento2-magic-methods#6]
Hi,

First of all: Thanks for this package. I've run into a problem where the latest version does not work with Magento 2.4.0 and higher:
```
composer require fooman/phpstan-magento2-magic-methods
Using version ^0.7.2 for fooman/phpstan-magento2-magic-methods
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fooman/phpstan-magento2-magic-methods ^0.7.2 -> satisfiable by fooman/phpstan-magento2-magic-methods[v0.7.2].
    - fooman/phpstan-magento2-magic-methods v0.7.2 requires phpstan/phpstan >=0.12.26 -> satisfiable by phpstan/phpstan[0.12.26, 0.12.27, 0.12.28, 0.12.29, 0.12.30, 0.12.31, 0.12.32, 0.12.33, 0.12.34, 0.12.35, 0.12.36, 0.12.37, 0.12.38, 0.12.39, 0.12.40, 0.12.41, 0.12.42, 0.12.43, 0.12.44, 0.12.45, 0.12.46, 0.12.47, 0.12.48, 0.12.49, 0.12.50, 0.12.51, 0.12.52, 0.12.53, 0.12.54, 0.12.55, 0.12.56, 0.12.57, 0.12.58, 0.12.59, 0.12.60, 0.12.61, 0.12.62, 0.12.63, 0.12.64, 0.12.65, 0.12.66, 0.12.67, 0.12.68, 0.12.69, 0.12.70, 0.12.71, 0.12.72, 0.12.73, 0.12.74, 0.12.75, 0.12.76, 0.12.77, 0.12.78, 0.12.79, 0.12.80, 0.12.81, 0.12.82, 0.12.83, 0.12.84, 0.12.85, dev-master, 0.12.x-dev] but these conflict with your requirements or minimum-stability.
```

When pinning the version at 0.7.1 it works fine though. This is most likely due to updating the used PHPStan version in this commit, but I'm not sure what is the cause of this conflict:
https://github.com/fooman/phpstan-magento2-magic-methods/commit/2b39a106cfb7819ba0405f506f670beb8b4fa1ec

**Comment by fooman** [comment]
@michielgerritsen is this installing it in the Magento root? The main use case this repo covers would be to have the module code separate to Magento Core.

The error message is unfortunately a bit short but my best guess would be that it runs up against this:
https://github.com/magento/magento2/blob/2.4.0/composer.json#L95

In that case using the older version would be a solution. Seeing that the initial require command defaults to 0.7.2 might be an idea to change the installation command to
`composer require fooman/phpstan-magento2-magic-methods:^0.7.0` which should let Composer find the right one.

**Comment by michielgerritsen** [comment]
Ah yes, I wasn't aware that installing in the root isn't the main use case. If I install this package into my extension (having the Magento repo added), it works as expected indeed.
